//     Underscore.js 1.13.2
//     https://underscorejs.org
//     (c) 2009-2021 Jeremy Ashkenas, Julian Gonggrijp, and DocumentCloud and Investigative Reporters & Editors
//     Underscore may be freely distributed under the MIT license.

export {
  after, allKeys, before,
  bind,
  bindAll,
  chain,
  chunk,
  clone, compact,
  compose,
  constant,
  contains, contains as include,
  contains as includes, countBy,
  create,
  debounce, defaults,
  defer,
  delay, difference, each, each as forEach, every as all, every,
  extend, extendOwn as assign, extendOwn,
  filter, filter as select, find as detect, find,
  findIndex,
  findKey,
  findLastIndex,
  findWhere,
  first, first as head, first as take, flatten, functions, functions as methods, get,
  groupBy,
  has, identity, indexBy,
  indexOf,
  initial, intersection,
  invert,
  invoke,
  isArguments,
  isArray,
  isArrayBuffer,
  isBoolean,
  isDataView,
  isDate,
  isElement,
  isEmpty,
  isEqual,
  isError,
  isFinite,
  isFunction,
  isMap,
  isMatch,
  isNaN,
  isNull,
  isNumber,
  isObject,
  isRegExp,
  isSet,
  isString,
  isSymbol,
  isTypedArray,
  isUndefined,
  isWeakMap,
  isWeakSet,
  iteratee,
  keys,
  last,
  lastIndexOf, map as collect, map,
  mapObject,
  matcher,
  matcher as matches,
  max,
  memoize, min,
  mixin,
  negate,
  noop,
  now,
  object,
  omit,
  once,
  pairs,
  partial,
  partition,
  pick,
  pluck,
  property,
  propertyOf,
  random,
  range, reduce as foldl, reduce as inject, reduce, reduceRight as foldr, reduceRight,
  reject, rest as drop, rest, rest as tail, restArguments,
  result,
  sample, shuffle,
  size, some as any, some,
  sortBy,
  sortedIndex, tap,
  template,
  templateSettings,
  throttle,
  times,
  toArray,
  toPath, union,
  uniq,
  uniq as unique,
  uniqueId, unzip as transpose, unzip,
  values, VERSION, where,
  without,
  wrap,
  zip, _ as default, _escape as escape, _unescape as unescape
} from './underscore-node-f.cjs';
//# sourceMappingURL=underscore-node.mjs.map
